### ISSUE TITLE
Unsupported concepts can be selected when adding concept to a glossary

### ISSUE THREAD

**Issue by cadamini** [translate/terminator#13]
The following message appears when I choose a subject field from the dropdown: 

> Specify only Subject fields that belong to the chosen glossary available subject fields.

Maybe it's useful to filter the list prior to presenting it to the user. If a concept is not supported, it should not appear here.

Reproduce it like this: 
1. go to a glossary
2. click **add a new concept to this glossary**
3. select a concept from the **subject field** drop-down.

**Comment by unho** [comment]
@cadamini I am afraid this project is no longer maintained. Feel free to fork it, and fix this issue.
